apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qg86fqviy-nodejs
  janus-idp.io/tekton: qg86fqviy-nodejs
  backstage.io/kubernetes-id: qg86fqviy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qg86fqviy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
